# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e4eec2ef1284bfb467bd1020a9a0682817e60d4e3d7d037f0bfe05e508c806a2bd5a6f102bb65f061709d11f06ede5c80ad247105d647d9c988a8f7a0be26ffe

test:
  secret_key_base: b04e50454340f42435dc7ef8adc10bfcbb4ff10d4c6aa1f21d69c1791e563bee8c530489617db5cd197a5e4f77815124f9f95f506b5029cd1f03659febda8d1e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
